//
//  SearchBookModels.swift
//  BookFinder
//
//  Created by Paul Jang on 2020/08/19.
//  Copyright (c) 2020 Paul Jang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BookInfo {
    struct Request {
        let q: String
        let page: Int
    }
    
    struct Response {
        let totalItems: Int
        var bookModel: [BookModel]
        let page: Int
    }
    
    struct ViewModel {
        let bookData: [BookModel]
        let itemTotalCount: Int
        let page: Int
    }
    
    struct BookModel {
        let title: String
        let author: [String]
        let publishedDate: String
        let thumbnail: String
        
        let pageCount: Int
        let subtitle: String
        let publisher: String
        let description: String
    }
}
