//
//  DetailBookRouter.swift
//  BookFinder
//
//  Created by Paul Jang on 2020/08/20.
//  Copyright (c) 2020 Paul Jang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailBookRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol DetailBookDataPassing
{
    var dataStore: DetailBookDataStore? { get }
}

class DetailBookRouter: NSObject, DetailBookRoutingLogic, DetailBookDataPassing
{
    weak var viewController: DetailBookViewController?
    var dataStore: DetailBookDataStore?
    
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: DetailBookViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: DetailBookDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
