//
//  DetailBookPresenter.swift
//  BookFinder
//
//  Created by Paul Jang on 2020/08/20.
//  Copyright (c) 2020 Paul Jang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftyJSON
protocol DetailBookPresentationLogic
{
    func presentUI(response: DetailBook.Response)
}

class DetailBookPresenter: DetailBookPresentationLogic
{
    weak var viewController: DetailBookDisplayLogic?
    
    // MARK: Do something
    
    func presentUI(response: DetailBook.Response)
    {
        let authorStr = response.bookModel.author.reduce("", { (s1: String, s2: String) -> String in
            if s1 == "" {
                return s1 + s2
            }
            return s1 + " , " + s2
        })
        
        
        var title = "\(response.bookModel.title)"
        if response.bookModel.subtitle != "" {
            title = "\(response.bookModel.title)\n\n\(response.bookModel.subtitle)"
        }
        
        let strArr = [("제목" , title), ("페이지수" , "\(response.bookModel.pageCount)"), ("발행일" , response.bookModel.publishedDate), ("출판사" , response.bookModel.publisher), ("설명" , response.bookModel.description), ("작가" , authorStr)]
        let viewModel = DetailBook.ViewModel(strArr: strArr, titleImage: response.bookModel.thumbnail)
        viewController?.displayBookInfo(viewModel: viewModel)
    }
}
