//
//  DetailBookWorker.swift
//  BookFinder
//
//  Created by Paul Jang on 2020/08/20.
//  Copyright (c) 2020 Paul Jang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailBookWorker
{
    func doSomeWork()
    {
    }
}
